# Generated by Django 5.2 on 2026-09-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=40)),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=200)),
                ('corpo', models.TextField(blank=True)),
                ('entregue', models.BooleanField(default=True)),
                ('erro', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'mensagem enviada',
                'verbose_name_plural': 'mensagens enviadas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('rotina', models.CharField(default='verificar_vencimentos', max_length=60)),
                ('duracao_seg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avaliados', models.PositiveIntegerField(default=0)),
                ('notificados', models.PositiveIntegerField(default=0)),
                ('ignorados', models.PositiveIntegerField(default=0)),
                ('sucesso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'execução de rotina',
                'verbose_name_plural': 'execuções de rotina',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('identificacao', models.CharField(max_length=150)),
                ('evento', models.CharField(max_length=80)),
                ('grupo', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'registro de acesso',
                'verbose_name_plural': 'registros de acesso',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('OK', 'Sucesso'), ('WARN', 'Alerta'), ('ERRO', 'Erro')], default='INFO', max_length=5)),
                ('evento', models.CharField(max_length=80)),
                ('detalhe', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro do sistema',
                'verbose_name_plural': 'registros do sistema',
                'ordering': ['-data_hora'],
            },
        ),
    ]
