# Generated by Django 5.2 on 2026-09-04 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=60)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('carga_horaria', models.CharField(default='4 horas', max_length=30)),
                ('validade_meses', models.PositiveSmallIntegerField(default=12)),
                ('nota_minima', models.DecimalField(decimal_places=1, default=7, max_digits=3)),
                ('max_tentativas', models.PositiveSmallIntegerField(default=3)),
                ('versao', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=140)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='treinamentos.curso')),
            ],
            options={
                'ordering': ['curso', 'ordem'],
                'unique_together': {('curso', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateField(default=django.utils.timezone.localdate)),
                ('atribuido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='treinamentos.curso')),
            ],
            options={
                'verbose_name': 'atribuição individual',
                'verbose_name_plural': 'atribuições individuais',
                'unique_together': {('curso', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='CursoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='treinamentos.curso')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='contas.departamento')),
            ],
            options={
                'verbose_name': 'curso por departamento',
                'verbose_name_plural': 'cursos por departamento',
                'unique_together': {('curso', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_acesso', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='treinamentos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presença',
                'verbose_name_plural': 'presenças',
                'unique_together': {('usuario', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slides_vistos', models.JSONField(default=list)),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='treinamentos.aula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progresso de aula',
                'verbose_name_plural': 'progressos de aula',
                'unique_together': {('usuario', 'aula')},
            },
        ),
        migrations.CreateModel(
            name='SlideAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=140)),
                ('corpo', models.TextField(blank=True, help_text='Aceita HTML simples: parágrafos e listas.')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='treinamentos.aula')),
            ],
            options={
                'verbose_name': 'slide',
                'ordering': ['aula', 'ordem'],
                'unique_together': {('aula', 'ordem')},
            },
        ),
    ]
