# Generated by Django 5.2 on 2026-09-04 23:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('texto', models.CharField(max_length=400)),
                ('correta', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['questao', 'letra'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoReacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_didatica', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nota_entendimento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True)),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'avaliação de reação',
                'verbose_name_plural': 'avaliações de reação',
                'ordering': ['-data_resposta'],
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('enunciado', models.TextField()),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['prova', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentativa', models.PositiveSmallIntegerField()),
                ('nota_obtida', models.DecimalField(decimal_places=1, max_digits=4)),
                ('data_realizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'resposta de prova',
                'verbose_name_plural': 'respostas de prova',
                'ordering': ['-data_realizacao'],
            },
        ),
    ]
