# Generated by Django 5.2 on 2026-09-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('treinamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoreacao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='treinamentos.curso'),
        ),
        migrations.AddField(
            model_name='avaliacaoreacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prova',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prova', to='treinamentos.curso'),
        ),
        migrations.AddField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='avaliacoes.prova'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='avaliacoes.questao'),
        ),
        migrations.AddField(
            model_name='respostaprova',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacoes.prova'),
        ),
        migrations.AddField(
            model_name='respostaprova',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='alternativa',
            unique_together={('questao', 'letra')},
        ),
    ]
