# Generated by Django 5.2 on 2026-09-02 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricula', models.CharField(editable=False, max_length=10, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('grupo', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('RH', 'RH')], default='COLABORADOR', max_length=12)),
                ('senha_provisoria', models.BooleanField(default=True)),
                ('pseudonimizado', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='contas.departamento')),
            ],
            options={
                'verbose_name_plural': 'usuários',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('utilizado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de verificação',
                'verbose_name_plural': 'códigos de verificação',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='Reidentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('pseudonimo', models.CharField(max_length=20)),
                ('nome_original', models.CharField(max_length=120)),
                ('email_original', models.EmailField(max_length=254)),
                ('cargo_original', models.CharField(blank=True, max_length=80)),
                ('data_desligamento', models.DateField(default=django.utils.timezone.localdate)),
                ('data_exclusao', models.DateField()),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desligamentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reidentificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reidentificação',
                'verbose_name_plural': 'reidentificações',
            },
        ),
    ]
