# Generated by Django 5.2 on 2026-09-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceitou_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_aceite_termos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
