# Generated by Django 5.2 on 2026-09-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_prova', models.DecimalField(decimal_places=1, max_digits=4)),
                ('versao_curso', models.PositiveIntegerField()),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
