# Generated by Django 5.2 on 2026-09-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacao', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco_dias', models.PositiveSmallIntegerField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='certificacao.certificado')),
            ],
            options={
                'verbose_name': 'notificação enviada',
                'verbose_name_plural': 'notificações enviadas',
                'unique_together': {('certificado', 'marco_dias')},
            },
        ),
    ]
